import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.7.1'
import jsPDF from 'https://esm.sh/jspdf@2.5.1'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const { consultationId, type = 'pdf' } = await req.json()

    if (!consultationId) {
      throw new Error('Consultation ID is required')
    }

    // Initialize Supabase client
    const supabaseUrl = Deno.env.get('SUPABASE_URL')
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')
    
    if (!supabaseUrl || !supabaseKey) {
      throw new Error('Missing environment variables')
    }

    const supabase = createClient(supabaseUrl, supabaseKey)

    // Fetch consultation data
    const { data: consultation, error: consultationError } = await supabase
      .from('consultations')
      .select(`
        *,
        consultation_contents (
          content,
          language,
          created_at
        )
      `)
      .eq('id', consultationId)
      .single()

    if (consultationError) {
      throw consultationError
    }

    // Generate document content
    const content = consultation.consultation_contents
      .sort((a: any, b: any) => new Date(a.created_at).getTime() - new Date(b.created_at).getTime())
      .map((content: any) => content.content)
      .join('\n\n')

    const consultationDate = new Date(consultation.created_at).toLocaleString('en-US', {
      dateStyle: 'full',
      timeStyle: 'short'
    })

    let documentBlob: Blob
    let mimeType: string
    let fileExtension: string

    if (type === 'pdf') {
      // Generate PDF
      const doc = new jsPDF()
      
      // Add VoxNote branding header
      doc.setFontSize(24)
      doc.setTextColor(59, 130, 246) // Sky blue color
      doc.text('VoxNote', 20, 20)
      
      doc.setFontSize(10)
      doc.setTextColor(100, 100, 100)
      doc.text('Medical Consultation Report', 20, 28)
      
      // Add horizontal line
      doc.setDrawColor(200, 200, 200)
      doc.line(20, 32, 190, 32)
      
      // Add consultation date
      doc.setFontSize(11)
      doc.setTextColor(60, 60, 60)
      doc.text(`Date: ${consultationDate}`, 20, 42)
      doc.text(`Consultation ID: ${consultationId.slice(0, 8)}...`, 20, 49)
      
      // Add another line
      doc.line(20, 53, 190, 53)
      
      // Add transcription content
      doc.setFontSize(12)
      doc.setTextColor(40, 40, 40)
      doc.text('Transcription:', 20, 63)
      
      // Split content into lines that fit the page width
      const splitContent = doc.splitTextToSize(content, 170)
      let yPosition = 73
      
      splitContent.forEach((line: string) => {
        if (yPosition > 270) {
          doc.addPage()
          yPosition = 20
        }
        doc.text(line, 20, yPosition)
        yPosition += 7
      })
      
      // Add footer
      const pageCount = doc.getNumberOfPages()
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i)
        doc.setFontSize(9)
        doc.setTextColor(150, 150, 150)
        doc.text(
          `Page ${i} of ${pageCount} | Generated by VoxNote`,
          105,
          285,
          { align: 'center' }
        )
      }
      
      const pdfOutput = doc.output('arraybuffer')
      documentBlob = new Blob([pdfOutput], { type: 'application/pdf' })
      mimeType = 'application/pdf'
      fileExtension = 'pdf'
    } else {
      // For DOCX, we'll create a simple text file for now
      // In production, you'd want to use a proper DOCX library
      const documentContent = `VoxNote Medical Consultation Report
Generated on: ${consultationDate}
Consultation ID: ${consultationId}

================================================================

${content}

================================================================
Generated by VoxNote - Voice-Powered Medical Documentation`.trim()
      
      documentBlob = new Blob([documentContent], { type: 'text/plain' })
      mimeType = 'text/plain'
      fileExtension = 'txt'
    }

    // Generate unique filename
    const fileName = `consultations/${consultation.user_id}/${consultationId}.${fileExtension}`

    // Upload to Storage
    const { error: uploadError } = await supabase.storage
      .from('documents')
      .upload(fileName, documentBlob, {
        contentType: mimeType,
        upsert: true
      })

    if (uploadError) {
      throw uploadError
    }

    // Get public URL (won't work for private bucket, but we'll store the path)
    const documentPath = fileName

    // Update consultation with document URL
    const { error: updateError } = await supabase
      .from('consultations')
      .update({
        document_url: documentPath,
        document_type: type
      })
      .eq('id', consultationId)

    if (updateError) {
      throw updateError
    }

    return new Response(
      JSON.stringify({ success: true, documentPath }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )

  } catch (error) {
    console.error('Error generating document:', error)
    return new Response(
      JSON.stringify({ error: error.message }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 500 }
    )
  }
})
