// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecnhdepmutimvswhkecg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjbmhkZXBtdXRpbXZzd2hrZWNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwMzI0NDksImV4cCI6MjA1NDYwODQ0OX0.zsKKpUxL6WEB26kh-B-cKQHWrmPM-VEDF7DdlFaxC0Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);